#  This is API docker file that is used to connect
#  the Swagger/Flask API to Gunicorn, via Supervisord.
#  Web3.py is then used to interact with the contracts
#  (written and tested in truffle)

FROM python:3.6

RUN  apt-get update -y && \
     apt-get upgrade -y

# issue with latest pip version
RUN pip install --upgrade pip~=20.2.0

# API
RUN mkdir -p /usr/src/package
COPY ./package /usr/src/package
WORKDIR /usr/src/package
RUN pip install -e .

# Start processes
CMD ["python3", "-m", "swagger_server"]