version: '3'

services:

  studentnft_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
      INFURA_KEY: "your infura API key"
      PRIVATE_KEY: "your Ethereum private key"
    depends_on:
      - mongodb
    networks:
      - backbone

  mongodb:
    image: mongo:3.6
    command: mongod
    networks:
      - backbone

networks:
  backbone:
    driver: bridge