version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
            echo 'export IMAGE_NAME=student-nft-api' >> $BASH_ENV 
            python -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t registree/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push registree/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no root@134.122.75.105 "sed 's/NFT_TAG=.*/NFT_TAG=$TAG/' -i './uct-deployment/.env';/bin/bash ./uct-deployment/RegistreeUpdateStaging.sh"